import {_electron as electron,expect} from '@playwright/test';
import {mkdtemp,mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
const profile=await mkdtemp(path.join(tmpdir(),'spidey-smoke-'));
const env={...process.env,AGORA_APP_ID:'',AGORA_APP_CERTIFICATE:'',AGORA_PIPELINE_ID:''};delete env.ELECTRON_RUN_AS_NODE;
const application=await electron.launch({args:['.',`--user-data-dir=${profile}`,'--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream'],env});
const errors=[];
try{
 await expect.poll(()=>application.windows().filter(p=>p.url().includes('index.html')).length).toBe(2);
 const page=application.windows().find(p=>!p.url().includes('pet=1')),pet=application.windows().find(p=>p.url().includes('pet=1'));
 for(const p of [page,pet])p.on('pageerror',e=>errors.push(e.message));
 await expect(page.getByRole('heading',{name:'Make room for little breaks.'})).toBeVisible();
 await expect(pet.getByRole('img',{name:/Spider-Man/})).toBeVisible();
 const placement=await application.evaluate(({BrowserWindow,screen})=>{const w=BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('pet=1'));return {bounds:w.getBounds(),screen:screen.getPrimaryDisplay().bounds,onTop:w.isAlwaysOnTop()};});
 expect(placement.bounds.y).toBe(placement.screen.y);expect(placement.bounds.x+150).toBe(Math.round(placement.screen.x+placement.screen.width/2));expect(placement.onTop).toBe(true);
 await expect.poll(()=>pet.evaluate(()=>getComputedStyle(document.documentElement).backgroundColor)).toBe('rgba(0, 0, 0, 0)');
 await page.getByRole('button',{name:'Add task',exact:true}).click();await page.getByPlaceholder('e.g. Send the project update').fill('Send the thoughtful update');await page.getByRole('button',{name:'Add my little task'}).click();
 await page.reload();await expect(page.getByText('Send the thoughtful update',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Complete Send the thoughtful update'}).click();await expect(page.getByRole('button',{name:'Reopen Send the thoughtful update'})).toBeVisible();
 await page.getByRole('button',{name:'Customize',exact:true}).click();await page.locator('input[name=minutes]').fill('2');await page.getByRole('button',{name:'Save my rhythm'}).click();await expect(page.getByRole('button',{name:'Every 2 min'})).toBeVisible();
 await page.getByRole('button',{name:'Pause for 1h'}).click();await expect(page.getByRole('button',{name:'Resume nudges'})).toBeVisible();await page.getByRole('button',{name:'Resume nudges'}).click();
 await page.evaluate(async()=>{const s=await window.mochi.getState();s.voiceEnabled=false;s.reminders[0].nextAt=Date.now()-1000;await window.mochi.saveState(s);});
 await expect(pet.getByText('Time for some water. Even superheroes need to hydrate!',{exact:true})).toBeVisible({timeout:5000});await pet.getByRole('button',{name:'In 5 minutes'}).click();
 expect((await page.evaluate(()=>window.mochi.getState())).reminders[0].nextAt-Date.now()).toBeGreaterThan(280000);
 await page.getByRole('button',{name:'Dismiss',exact:true}).click();await mkdir('docs/screenshots',{recursive:true});await page.screenshot({path:'docs/screenshots/overview.png',fullPage:true});
 await page.getByRole('button',{name:'Pet studio',exact:true}).click();await page.getByLabel('Studio conversation language').selectOption('hi');await expect(pet.getByLabel('Conversation language')).toHaveValue('hi');await expect(pet.getByText('आपके काम, मेरे ज़िम्मे। बात करें?')).toBeVisible();
 await page.screenshot({path:'docs/screenshots/pet-studio.png',fullPage:true});await pet.screenshot({path:'docs/screenshots/desktop-pet.png',omitBackground:true});
 await pet.getByLabel('Conversation language').selectOption('en');await pet.getByRole('button',{name:'Talk to Spider-Man',exact:true}).click();await expect(pet.getByText(/Add your Agora App ID/)).toBeVisible({timeout:15000});
 expect(errors).toEqual([]);console.log('PASS: transparent notch placement, Spider-Man, task persistence, completion, intervals, pause, delivery, snooze, English/Hindi synchronization, missing-credential feedback, no renderer errors.');
}finally{await application.close();}
