import { _electron as electron, expect } from '@playwright/test';
import { mkdtemp, mkdir, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
const profile=await mkdtemp(path.join(tmpdir(),'mochi-smoke-'));
const launchEnv={...process.env,AGORA_APP_ID:'',AGORA_APP_CERTIFICATE:'',AGORA_PIPELINE_ID:''};
delete launchEnv.ELECTRON_RUN_AS_NODE;
const application=await electron.launch({args:['.',`--user-data-dir=${profile}`],env:launchEnv});
const errors=[];
try{
 await expect.poll(()=>application.windows().filter(p=>p.url().includes('index.html')).length).toBe(2);
 const page=application.windows().find(p=>!p.url().includes('pet=1'));
 page.on('pageerror',e=>errors.push(e.message));
 await expect(page.getByRole('heading',{name:'Make room for little breaks.'})).toBeVisible();
 await expect.poll(()=>application.windows().length).toBe(2);
 const pet=application.windows().find(p=>p.url().includes('pet=1'));
 pet.on('pageerror',e=>errors.push(e.message));
 await expect(pet.getByRole('img')).toBeVisible();
 await expect.poll(()=>pet.evaluate(()=>getComputedStyle(document.documentElement).backgroundColor)).toBe('rgba(0, 0, 0, 0)');
 const properties=await application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().map(w=>({transparent:w.getBackgroundColor(),alwaysOnTop:w.isAlwaysOnTop(),frame:w.getBounds()})));
 expect(properties.some(w=>w.alwaysOnTop)).toBe(true);
 await page.getByRole('button',{name:'Add task',exact:true}).click();
 await page.getByPlaceholder('e.g. Send the project update').fill('Send the thoughtful update');
 await page.getByRole('button',{name:'Add my little task'}).click();
 await expect(page.getByText('Send the thoughtful update',{exact:true})).toBeVisible();
 await page.reload();
 await expect(page.getByText('Send the thoughtful update',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Complete Send the thoughtful update'}).click();
 await expect(page.getByRole('button',{name:'Reopen Send the thoughtful update'})).toBeVisible();
 await page.getByRole('button',{name:'Customize',exact:true}).click();
 await page.locator('input[name=minutes]').fill('2');
 await page.getByRole('button',{name:'Save my rhythm'}).click();
 await expect(page.getByRole('button',{name:'Every 2 min'})).toBeVisible();
 await page.getByRole('button',{name:'Say hello',exact:true}).click();
 await expect(pet.getByText('A LITTLE NUDGE',{exact:true})).toBeVisible();
 await expect.poll(()=>pet.locator('.floating-status').textContent()).toContain('.env');
 await page.getByRole('button',{name:'Pause for 1h'}).click();
 await expect(page.getByRole('button',{name:'Resume nudges'})).toBeVisible();
 await page.getByRole('button',{name:'Resume nudges'}).click();
 // Force a due event via the same validated bridge used by the UI.
 await page.evaluate(async()=>{const s=await window.mochi.getState();s.voiceEnabled=false;s.reminders[0].nextAt=Date.now()-1000;await window.mochi.saveState(s);});
 await expect(pet.getByText('A little sip, a little reset. Time to drink some water!',{exact:true})).toBeVisible({timeout:5000});
 await pet.getByRole('button',{name:'In 5 minutes'}).click();
 const state=await page.evaluate(()=>window.mochi.getState());
 expect(state.reminders[0].nextAt-Date.now()).toBeGreaterThan(280000);
 expect(state.history).toHaveLength(1);
 // Dismiss dashboard nudge for an unobstructed screenshot.
 await page.getByRole('button',{name:'Dismiss',exact:true}).click();
 await mkdir('docs/screenshots',{recursive:true});
 await page.screenshot({path:'docs/screenshots/overview.png',fullPage:true});
 await page.getByRole('button',{name:'Pet studio',exact:true}).click();
 await page.getByRole('button',{name:/Peaches A little pocket/}).click();
 await expect(pet.getByRole('img')).toHaveAttribute('aria-label',/peach/);
 await page.screenshot({path:'docs/screenshots/pet-studio.png',fullPage:true});
 await page.getByRole('button',{name:/Mochi A soft spot/}).click();
 await pet.screenshot({path:'docs/screenshots/desktop-pet.png',omitBackground:true});
 expect(errors).toEqual([]);
 console.log('PASS: desktop windows, task persistence, completion, intervals, preview, missing credentials, pause, scheduled delivery, snooze, pet sync, no renderer errors.');
 console.log(`Isolated profile: ${profile}`);
}finally{await application.close();}
