import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, Bell, Check, ChevronRight, Clock3, Droplets, Footprints, Leaf, ListTodo, Moon, Plus, Settings2, Sparkles, Sprout, Volume2, VolumeX, X, Eye, Play, Monitor, Heart, Trash2 } from 'lucide-react';
import { bridge } from './bridge';
import { Pet } from './Pet';
import type { AppState, Nudge, PetName, Reminder, VoiceStatus } from './types';
const isPet=new URLSearchParams(location.search).has('pet');
const names={mochi:'Mochi',peach:'Peaches',cloud:'Nimbus'};
const icons={water:Droplets,walk:Footprints,eyes:Eye};
function timeUntil(at:number,now:number){const min=Math.max(0,Math.ceil((at-now)/60000));return min<1?'Due now':min<60?`in ${min} min`:`in ${Math.floor(min/60)}h${min%60?` ${min%60}m`:''}`;}
export default function App(){
 const [state,setState]=useState<AppState>(),[now,setNow]=useState(Date.now()),[tab,setTab]=useState('Overview'),[modal,setModal]=useState<'task'|'reminder'|'voice'|null>(null),[edit,setEdit]=useState<Reminder>(),[nudge,setNudge]=useState<Nudge|null>(null),[toast,setToast]=useState(''),[status,setStatus]=useState<VoiceStatus>({configured:false,missing:[]}),[voiceText,setVoiceText]=useState(''),[speaking,setSpeaking]=useState(false);
 const modalElement=useRef<HTMLElement>(null);
 const current=useRef(state);current.current=state;
 const toastTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
 function notify(text:string){setToast(text);clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),5000);}
 useEffect(()=>{bridge.getState().then(setState).catch(()=>notify('Could not load your settings.'));bridge.voiceStatus().then(setStatus);const off=bridge.onState(setState),offVoice=bridge.onVoice(setVoiceText);const timer=setInterval(()=>setNow(Date.now()),1000);return()=>{off();offVoice();clearInterval(timer);};},[]);
 useEffect(()=>{return bridge.onNudge(value=>{setNudge(value);if(isPet&&current.current?.voiceEnabled&&window.mochi){void import('./voice').then(module=>{module.setAudioOptions(current.current!.voiceEnabled,current.current!.volume);return module.speakThroughAgora(value.message,setSpeaking);}).catch(()=>notify('Unable to load voice.'));}});},[]);
 useEffect(()=>{if(isPet&&window.mochi&&state)void import('./voice').then(module=>module.setAudioOptions(state.voiceEnabled,state.volume));},[state?.voiceEnabled,state?.volume]);
 useEffect(()=>{document.body.classList.toggle('pet-window',isPet);document.documentElement.classList.toggle('pet-window',isPet);},[]);
 useEffect(()=>{
  if(!modal)return;
  const previous=document.activeElement as HTMLElement|null;
  const frame=requestAnimationFrame(()=>{const el=modalElement.current; if(el&&!el.contains(document.activeElement))el.querySelector<HTMLElement>('input,button,select')?.focus();});
  return()=>{cancelAnimationFrame(frame);previous?.focus();};
 },[modal]);
 if(!state)return <div className="loading"><Sprout/> Waking up Mochi…</div>;
 const petName=names[state.pet],paused=state.pausedUntil>now,completed=state.tasks.filter(t=>t.done).length;
 async function save(next:AppState){try{setState(await bridge.saveState(next));}catch(error){notify(error instanceof Error?error.message:'Could not save.');}}
 const patch=(value:Partial<AppState>)=>save({...state,...value});
 function snooze(){if(nudge){const nextAt=Date.now()+5*60000;void patch({reminders:state!.reminders.map(r=>r.id===nudge.id?{...r,nextAt}:r),tasks:state!.tasks.map(t=>t.id===nudge.id?{...t,nextAt}:t)});setNudge(null);}}
 function done(){if(nudge){void patch({tasks:state!.tasks.map(t=>t.id===nudge.id?{...t,done:true}:t)});setNudge(null);}}
 const preview=(kind='hello')=>{void bridge.preview(kind).catch(()=>notify('Could not preview reminder.'));if(!window.mochi)notify('Visual preview · Agora voice is available in the desktop app.');};
 if(isPet)return <div className="floating-pet"><div className="floating-controls"><button aria-label="Open Mochi dashboard" onClick={()=>void bridge.openDashboard()}><Settings2 size={17}/></button><span className="drag-handle">drag me anywhere</span><button aria-label="Mute voice" onClick={()=>void patch({voiceEnabled:!state.voiceEnabled})}>{state.voiceEnabled?<Volume2 size={17}/>:<VolumeX size={17}/>}</button></div>{nudge?<div className="speech-bubble" role="status"><button className="bubble-close" aria-label="Dismiss reminder" onClick={()=>setNudge(null)}><X size={14}/></button><small>A LITTLE NUDGE</small><p>{nudge.message}</p><div><button onClick={done}>Done <Check size={13}/></button><button onClick={snooze}>In 5 minutes</button></div></div>:<div className="idle-bubble">{paused?'Taking a little nap. ☾':'A little friend, right here.'}</div>}<div className="draggable-pet"><Pet variant={state.pet} speaking={speaking} sleeping={paused}/></div>{state.voiceEnabled&&voiceText&&<span className="floating-status">{voiceText}</span>}</div>;
 return <div className="app-shell">
  <aside className="sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();setTab('Overview');}}><span className="brand-icon"><Sprout size={25}/></span>mochi</a><div className="workspace-label">YOUR LITTLE CORNER</div><nav>{[{label:'Overview',icon:Leaf},{label:'Reminders',icon:Bell},{label:'My tasks',icon:ListTodo},{label:'Pet studio',icon:Sparkles}].map(({label,icon:Icon})=><button key={label} className={tab===label?'nav-item active':'nav-item'} onClick={()=>setTab(label)}><Icon size={19}/>{label}{label==='My tasks'&&state.tasks.filter(t=>!t.done).length>0&&<span className="nav-count">{state.tasks.filter(t=>!t.done).length}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="sidebar-note"><Sprout size={23}/><p>Small breaks.<br/>Happier days.</p><span>A little care goes a long way.</span></div><button className="nav-item" onClick={()=>setModal('voice')}><Settings2 size={18}/>Voice & settings</button><div className="profile"><div className="profile-avatar">Y</div><div><strong>Your cozy space</strong><span>Made for your everyday</span></div><Heart size={16}/></div></div></aside>
  <main><header className="topbar"><span>Your companion, your pace.</span><div><span className={`status-dot ${paused?'paused':''}`}/>{paused?'Taking a break':'Here for you'}<span className="top-divider"/><button title="Voice settings" onClick={()=>setModal('voice')}><Settings2 size={18}/></button></div></header>
  <div className="page-content"><div className="page-heading"><div><div className="eyebrow"><span/> A LITTLE COMPANY, A LOT OF CARE</div><h1>{tab==='Overview'?'Make room for little breaks.':tab==='Reminders'?'A nudge in the right direction.':tab==='My tasks'?'One little thing at a time.':'Meet your desk-mate.'}</h1><p>{tab==='Overview'?`${petName}’s here to keep you company and help you feel your best.`:tab==='Reminders'?'Gentle reminders that fit into your day.':tab==='My tasks'?'Less on your mind. More room to breathe.':'A small companion with a personality all their own.'}</p></div><button className="button secondary compact" onClick={()=>void patch({pausedUntil:paused?0:Date.now()+3600000})}>{paused?<Play size={15}/>:<Moon size={15}/>} {paused?'Resume nudges':'Pause for 1h'}</button></div>
  {(tab==='Overview'||tab==='Pet studio')&&<section className="hero-card"><div className="hero-copy"><span className="pill"><span className="status-dot"/> YOUR DESKTOP COMPANION</span><h2>A little friend.<br/>A gentler day.</h2><p>A sip of water. A stretch. A moment for you.<br/>{petName} remembers the little things.</p><div className="hero-actions"><button className="button primary" onClick={()=>{void bridge.showPet();if(!window.mochi)notify('Browser preview opened. Run npm run desktop for a floating desktop pet.');}}><Monitor size={16}/> Meet {petName}<ArrowUpRight size={16}/></button><button className="text-button" onClick={()=>preview()}><Volume2 size={17}/> Say hello</button></div><div className="hero-footnote"><span className="tiny-spark">✧</span> A tiny companion. Always on your side.</div></div><div className="pet-scene"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><span className="scene-star star-one">✧</span><span className="scene-star star-two">✦</span><span className="scene-dot"/><div className="hello-bubble">{paused?'A little rest is good.':'You’re doing great, human.'}<span>{paused?'☾':'♡'}</span></div><Pet variant={state.pet} sleeping={paused}/><div className="pet-name"><span className="status-dot"/>{petName}<span>·</span>{paused?'napping':'happy to be here'}</div></div></section>}
  {tab==='Pet studio'&&<section className="section"><div className="section-heading"><h2>Find your kind of cozy</h2><span>Same little heart. A different look.</span></div><div className="pet-options">{(['mochi','peach','cloud'] as PetName[]).map(p=><button className={`pet-option ${state.pet===p?'selected':''}`} key={p} onClick={()=>void patch({pet:p})}><Pet variant={p} small/><strong>{names[p]}</strong><span>{p==='mochi'?'A soft spot for small moments':p==='peach'?'A little pocket of sunshine':'Your calm in a busy day'}</span>{state.pet===p&&<span className="selected-label"><Check size={13}/>Your companion</span>}</button>)}</div></section>}
  {(tab==='Overview'||tab==='Reminders')&&<section className="section"><div className="section-heading"><div><h2>Your daily nudges <span className="count-badge">{state.reminders.filter(r=>r.enabled).length} active</span></h2><p>Little reminders. Big difference.</p></div><button className="text-button" onClick={()=>{setEdit(state.reminders[0]);setModal('reminder');}}><Settings2 size={15}/> Customize</button></div><div className="reminder-grid">{state.reminders.map(r=>{const Icon=icons[r.kind];return <article className={`reminder-card ${!r.enabled?'disabled':''}`} key={r.id}><div className="reminder-top"><span className={`reminder-icon ${r.kind}`}><Icon size={21}/></span><button role="switch" aria-label={`${r.title} reminders`} aria-checked={r.enabled} className={`toggle ${r.enabled?'on':''}`} onClick={()=>void patch({reminders:state.reminders.map(x=>x.id===r.id?{...x,enabled:!x.enabled,nextAt:Date.now()+x.minutes*60000}:x)})}><span/></button></div><h3>{r.title}</h3><p>{r.kind==='water'?'A little hydration goes a long way.':r.kind==='walk'?'A small walk. A fresh perspective.':'Look away. Let your eyes unwind.'}</p><div className="reminder-footer"><button className="interval" onClick={()=>{setEdit(r);setModal('reminder');}}><Clock3 size={13}/>Every {r.minutes} min<ChevronRight size={13}/></button><span>{!r.enabled?'Paused':paused?'Snoozing':timeUntil(r.nextAt,now)}</span></div></article>;})}</div>{tab==='Reminders'&&<div className="tip-box"><Leaf size={20}/><p>Pick a rhythm that feels good. You can pause all nudges for an hour whenever you need some focus.</p></div>}</section>}
  {(tab==='Overview'||tab==='My tasks')&&<div className="lower-grid"><section className="task-panel"><div className="section-heading"><div><h2>A little off your plate <span className="count-badge neutral">{state.tasks.filter(t=>!t.done).length}</span></h2><p>{completed?`${completed} little ${completed===1?'win':'wins'} today. Keep going gently.`:'Your to-dos, with a friendly nudge.'}</p></div><button className="icon-button" title="Add task" onClick={()=>setModal('task')}><Plus size={18}/></button></div>{!state.tasks.length?<div className="empty-tasks"><span><ListTodo size={23}/></span><div><strong>A little more headspace.</strong><p>Add a task. {petName} will help you remember.</p></div><button className="button secondary compact" onClick={()=>setModal('task')}><Plus size={14}/> Add a task</button></div>:<div className="task-list">{state.tasks.map(t=><div className={`task-row ${t.done?'done':''}`} key={t.id}><button className="task-check" aria-label={`${t.done?'Reopen':'Complete'} ${t.title}`} onClick={()=>void patch({tasks:state.tasks.map(x=>x.id===t.id?{...x,done:!x.done,nextAt:Date.now()+30*60000}:x)})}>{t.done&&<Check size={13}/>}</button><span>{t.title}</span><small>{t.done?'Done':timeUntil(t.nextAt,now)}</small><button className="delete-task" title={`Delete ${t.title}`} onClick={()=>void patch({tasks:state.tasks.filter(x=>x.id!==t.id)})}><Trash2 size={14}/></button></div>)}</div>}<button className="add-task" onClick={()=>setModal('task')}><Plus size={15}/> Add something to remember</button></section><section className="voice-card"><span className="voice-symbol"><Volume2 size={22}/><i/><i/><i/></span><h3>A familiar little voice.</h3><p>Gentle words, right when you need them.<br/>Brought to life with Agora.</p><button className="text-button" onClick={()=>setModal('voice')}>{status.configured?'Tune your pet’s voice':'Set up your pet’s voice'}<ArrowUpRight size={15}/></button><div className="agora-label"><span className={`status-dot ${status.configured?'':'paused'}`}/>{status.configured?'Agora ready':'Voice setup needed'}<span>agora</span></div></section></div>}
  {tab==='Reminders'&&<section className="history-panel"><h2>Recent little nudges</h2>{state.history.length?state.history.slice(0,10).map(h=><div className="history-row" key={h.id}><Bell size={15}/><span>{h.title}</span><small>{new Date(h.at).toLocaleString([],{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}</small></div>):<p>Your reminder history will appear here. A fresh start feels nice.</p>}</section>}
  <footer><Sprout size={15}/><span>You don’t have to do it all. Just the next little thing.</span><span className="footer-right">Made for a softer workday <span>✧</span></span></footer>
  </div></main>
  {nudge&&<div className="nudge-toast" role="status"><span className="nudge-icon"><Leaf size={22}/></span><div><strong>A little nudge from {petName}</strong><p>{nudge.message}</p><button onClick={done}>Done <Check size={13}/></button><button onClick={snooze}>Snooze 5 min</button></div><button title="Dismiss" onClick={()=>setNudge(null)}><X size={16}/></button></div>}
  {toast&&<div className="toast" role="status">{toast}<button aria-label="Dismiss" onClick={()=>setToast('')}><X size={14}/></button></div>}
  {modal&&<div className="modal-backdrop" onClick={()=>setModal(null)}><section ref={modalElement} className="modal" role="dialog" aria-modal="true" aria-label={modal==='task'?'Add a task':modal==='voice'?'Voice settings':'Customize reminder'} onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')setModal(null);
     if(e.key==='Tab'){const elements=Array.from(e.currentTarget.querySelectorAll<HTMLElement>('button,input,select,[tabindex="0"]')).filter(el=>!el.hasAttribute('disabled'));const first=elements[0],last=elements.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}
    }}><button className="modal-close" aria-label="Close dialog" onClick={()=>setModal(null)}><X size={20}/></button>
   {modal==='task'&&<><span className="modal-icon"><ListTodo/></span><h2>One less thing to remember.</h2><p>Leave a little to-do with {petName}.</p><form onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget),title=String(data.get('title')).trim(),minutes=Number(data.get('minutes'));if(!title)return;void patch({tasks:[...state.tasks,{id:crypto.randomUUID(),title,done:false,nextAt:Date.now()+minutes*60000}]}).then(()=>setModal(null));}}><label>What’s on your mind?<input name="title" autoFocus required maxLength={120} placeholder="e.g. Send the project update"/></label><label>Give me a nudge in<select name="minutes" defaultValue="30"><option value="1">1 minute</option><option value="15">15 minutes</option><option value="30">30 minutes</option><option value="60">1 hour</option><option value="120">2 hours</option></select></label><div className="form-hint">Repeats every 30 minutes until you mark it done.</div><button className="button primary full" type="submit"><Plus size={16}/>Add my little task</button></form></>}
   {modal==='reminder'&&edit&&<><span className="modal-icon"><Bell/></span><h2>Find your everyday rhythm.</h2><p>Make your nudges work for you.</p><form onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget),minutes=Number(data.get('minutes'));void patch({reminders:state.reminders.map(r=>r.id===edit.id?{...r,minutes,nextAt:Date.now()+minutes*60000}:r)}).then(()=>setModal(null));}}><label>Your reminder<select value={edit.id} onChange={e=>setEdit(state.reminders.find(r=>r.id===e.target.value))}>{state.reminders.map(r=><option key={r.id} value={r.id}>{r.title}</option>)}</select></label><label>Remind me every (minutes)<input key={edit.id} name="minutes" type="number" min="1" max="1440" defaultValue={edit.minutes} required/></label><button type="button" className="preview-button" onClick={()=>preview(edit.kind)}><Play size={14}/> Preview this nudge</button><button className="button primary full" type="submit">Save my rhythm<Check size={16}/></button></form></>}
   {modal==='voice'&&<><span className="modal-icon"><Volume2/></span><h2>A voice for your little friend.</h2><p>Warm, gentle reminders delivered through Agora.</p><div className="setting-row"><div><strong>Spoken reminders</strong><small>Visual nudges always stay available.</small></div><button role="switch" aria-label="Spoken reminders" aria-checked={state.voiceEnabled} className={`toggle ${state.voiceEnabled?'on':''}`} onClick={()=>void patch({voiceEnabled:!state.voiceEnabled})}><span/></button></div><label className="volume-label">Voice volume <span>{state.volume}%</span><input aria-label="Voice volume" type="range" min="0" max="100" value={state.volume} onChange={e=>void patch({volume:Number(e.target.value)})}/></label><div className="connection-box"><strong><span className={`status-dot ${status.configured?'':'paused'}`}/>{status.configured?'Agora credentials configured':'Let’s connect Agora'}</strong><p>{status.configured?'Your pet will connect when there’s something to say. No microphone is needed for spoken reminders.':'Add AGORA_APP_ID and AGORA_APP_CERTIFICATE to your local .env file, then restart the desktop app. The included README walks you through it.'}</p>{!window.mochi&&<small>You’re in the browser preview. Use <code>npm run desktop</code> for voice and the floating pet.</small>}</div>{voiceText&&<p className="voice-result" role="status">{voiceText}</p>}<button className="button primary full" onClick={()=>preview('hello')}><Volume2 size={16}/>{status.configured?'Say hello with Agora':'Preview a visual nudge'}</button><div className="privacy-note">Your microphone stays off. Credentials stay on your computer.</div></>}
  </section></div>}
 </div>;
}
